import { v4 as uuidv4 } from 'uuid';
import { ICustomer } from '../interfaces/customer';

export const customers: ICustomer[] = [
  {
    id: uuidv4(),
    name: "John Doe",
    title: "Software Engineer",
    address: "123 Main Street, Anytown, USA",
  },
  {
    id: uuidv4(),
    name: "Jane Smith",
    title: "Project Manager",
    address: "456 Elm Street, Somewhere, USA",
  },
  {
    id: uuidv4(),
    name: "David Lee",
    title: "Data Analyst",
    address: "789 Oak Avenue, Somewhere Else, USA",
  },
  {
    id: uuidv4(),
    name: "Emily Brown",
    title: "Marketing Manager",
    address: "1011 Pine Drive, Sunnyville, USA",
  },
  {
    id: uuidv4(),
    name: "Michael Wilson",
    title: "Sales Director",
    address: "1213 Maple Lane, Oakhaven, USA",
  },
  {
    id: uuidv4(),
    name: "Jessica Davis",
    title: "UI/UX Designer",
    address: "1415 Birch Road, Willow Creek, USA",
  },
  {
    id: uuidv4(),
    name: "Christopher Jones",
    title: "Product Manager",
    address: "1617 Cedar Street, Evergreen, USA",
  },
  {
    id: uuidv4(),
    name: "Ashley Williams",
    title: "Operations Manager",
    address: "1819 Redwood Avenue, Redwood City, USA",
  },
  {
    id: uuidv4(),
    name: "Matthew Garcia",
    title: "Finance Manager",
    address: "2021 Oak Ridge Trail, Oak Ridge, USA",
  },
  {
    id: uuidv4(),
    name: "Sarah Rodriguez",
    title: "HR Manager",
    address: "2223 Willow Creek Lane, Willow Creek, USA",
  },
  {
    id: uuidv4(),
    name: "Daniel Martin",
    title: "IT Manager",
    address: "2425 Pine Ridge Drive, Pine Ridge, USA",
  },
  {
    id: uuidv4(),
    name: "Jennifer Lopez",
    title: "Customer Success Manager",
    address: "2627 Maple Creek Road, Maple Creek, USA",
  },
  {
    id: uuidv4(),
    name: "Robert Hernandez",
    title: "Business Analyst",
    address: "2829 Oakwood Drive, Oakwood, USA",
  },
  {
    id: uuidv4(),
    name: "Elizabeth Wilson",
    title: "Marketing Coordinator",
    address: "3031 Willow Creek Lane, Willow Creek, USA",
  },
  {
    id: uuidv4(),
    name: "William Thomas",
    title: "Sales Representative",
    address: "3233 Pine Ridge Drive, Pine Ridge, USA",
  },
  {
    id: uuidv4(),
    name: "Maria Garcia",
    title: "Project Coordinator",
    address: "3435 Oakwood Drive, Oakwood, USA",
  },
  {
    id: uuidv4(),
    name: "Joseph Rodriguez",
    title: "Technical Writer",
    address: "3637 Redwood Avenue, Redwood City, USA",
  },
  {
    id: uuidv4(),
    name: "Linda Davis",
    title: "Account Manager",
    address: "3839 Maple Creek Road, Maple Creek, USA",
  },
  {
    id: uuidv4(),
    name: "Charles Martin",
    title: "Software Developer",
    address: "4041 Pine Ridge Drive, Pine Ridge, USA",
  },
  {
    id: uuidv4(),
    name: "Barbara Wilson",
    title: "UX Researcher",
    address: "4243 Oakwood Drive, Oakwood, USA",
  },
  {
    id: uuidv4(),
    name: "Richard Hernandez",
    title: "Product Designer",
    address: "4445 Redwood Avenue, Redwood City, USA",
  },
  {
    id: uuidv4(),
    name: "Patricia Lopez",
    title: "Marketing Specialist",
    address: "4647 Maple Creek Road, Maple Creek, USA",
  },
  {
    id: uuidv4(),
    name: "Thomas Garcia",
    title: "Data Scientist",
    address: "4849 Pine Ridge Drive, Pine Ridge, USA",
  },
  {
    id: uuidv4(),
    name: "Susan Rodriguez",
    title: "Project Lead",
    address: "5051 Oakwood Drive, Oakwood, USA",
  },
  {
    id: uuidv4(),
    name: "James Wilson",
    title: "Senior Software Engineer",
    address: "5253 Redwood Avenue, Redwood City, USA",
  },
  {
    id: uuidv4(),
    name: "Mary Hernandez",
    title: "UI Designer",
    address: "5455 Maple Creek Road, Maple Creek, USA",
  },
  {
    id: uuidv4(),
    name: "David Lopez",
    title: "QA Analyst",
    address: "5657 Pine Ridge Drive, Pine Ridge, USA",
  },
  {
    id: uuidv4(),
    name: "Karen Garcia",
    title: "Product Owner",
    address: "5859 Oakwood Drive, Oakwood, USA",
  },
];
